version: '3.9'

services:

  dns:
    build:
      context: dns

  bank:
    build:
      context: bank

  proxy:
    build:
      context: nginx

  powerziossh:
    build:
      context: powerzio-ssh
