version: '3.3'

services:

  bank:
    build:
      context: bank
    volumes:
      - ./bank/db.sqlite:/app/db.sqlite
    restart: always

  proxy:
    build:
      context: nginx
    volumes:
      - ./nginx/files:/var/project-files
    ports:
      - "80:80"
      - "443:443"
    restart: always
